# The Docker image that will be used to build your app
image: node:22.14.0

before_script:
  # Functions that should be executed before the build script is run
  - npm ci

create-pages:
  stage: build
  script:
    # Specify the steps involved to build your app here
    - npm run build
  # Specifies that this is a Pages job
  pages:
    # Publish the contents of the "out" folder to the web using Pages
    publish: out
  # Trigger rules
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
